/// Icone (emoji) degli alimenti: prima per nome, poi per categoria.
library;

String catEmoji(String cat) => switch (cat) {
      'Cereali e pasta' => '🌾',
      'Pane e prodotti da forno' => '🍞',
      'Legumi e proteine vegetali' => '🫘',
      'Verdure' => '🥦',
      'Frutta' => '🍎',
      'Frutta secca e semi' => '🥜',
      'Carne' => '🍗',
      'Salumi' => '🥓',
      'Pesce' => '🐟',
      'Uova' => '🥚',
      'Latte e yogurt' => '🥛',
      'Formaggi' => '🧀',
      'Oli, grassi e condimenti' => '🫒',
      'Dolci e snack' => '🍫',
      'Bevande' => '🥤',
      'Integratori' => '💪',
      'Piatti pronti' => '🍝',
      'Prodotti' => '🏷️',
      'Ricette' => '🍲',
      _ => '🍽️',
    };

// L'ordine conta: prima i piatti e i prodotti composti ("pasta al pomodoro",
// "yogurt alla fragola"), poi i singoli ingredienti.
final List<(RegExp, String)> _rules = [
  for (final (p, e) in const [
    // piatti e prodotti composti
    (r'\bbevanda di', '🥛'),
    (r'^olio\b', '🫒'),
    (r'\b(ham)?burger', '🍔'),
    (r'\b(toast|tramezzin|panin[oi]|sandwich)', '🥪'),
    (r'\bgallett', '🍘'),
    (r'\bfette biscottate', '🍞'),
    (r'\bkebab|\bpiadin|\bwrap\b|\btortilla|\bpita\b|pane arabo', '🌯'),
    (r'\bpizz', '🍕'),
    (r'\bsushi|\bnigiri|\bmaki\b', '🍣'),
    (r'\bpoke', '🥗'),
    (r'\barancin', '🍙'),
    (r'\bparmigiana\b', '🍆'),
    (r'\bcaprese\b', '🍅'),
    (r'\bminestron|\bzuppa|\bvellutata|\bbrodo', '🍲'),
    (r'\binsalata di riso|\brisott|\briso\b|\bpaella', '🍚'),
    (r'\bgnocch|\btortellin|\braviol|\bcappellett|\bagnolott', '🥟'),
    (r'\bpasta\b|\blasagn|\bspaghett|\bpenne\b|\bfusill|\brigaton|\bcarbonara|\bnoodle', '🍝'),
    (r'\bpolpett', '🍖'),
    (r'\bcotolett|\bnuggets?\b|\bpollo|\btacchino', '🍗'),
    (r'\bfrittata|\bomelette', '🍳'),
    (r'\bfiocchi di latte', '🧀'),
    (r'\byogurt|\bskyr\b|\bkefir', '🥛'),
    (r'\bgelat', '🍨'),
    (r'\bbudin', '🍮'),
    (r'\btiramis|\btorta\b|\bcrostata|\bpan di spagna|\bplumcake|\bpanetton|\bpandoro|\bcheesecake', '🍰'),
    (r'\bmuffin|\bmerendin|\bcupcake', '🧁'),
    (r'\bcornett|\bcroissant|\bbrioche', '🥐'),
    (r'\bpancake', '🥞'),
    (r'\bwafer|\bwaffle', '🧇'),
    (r'\bbiscott', '🍪'),
    (r'\bcrema spalmabile|\bnutella|\bcioccolat|\bcacao\b|\bbarrett', '🍫'),
    (r'\bcaramell|\bzucchero\b', '🍬'),
    (r'\bpopcorn', '🍿'),
    (r'\bpatatine', '🍟'),
    (r'\bmarmellat|\bconfettur', '🍓'),
    // bevande
    (r'\bspremut', '🍊'),
    (r'\blimone\b', '🍋'),
    (r'\bsucc[oh]i?\b|\bestratto|\bcentrifugat', '🧃'),
    (r'\bbirr', '🍺'),
    (r'\bprosecco|\bspumante|\bchampagne|\bspritz', '🥂'),
    (r'\bvino\b', '🍷'),
    (r'\bsuperalcolic|\bwhisk|\bvodka|\brum\b|\bgin\b|\bgrappa|\bamaro\b|\bliquore', '🥃'),
    (r'\bcaff|\bespresso|\bcappuccin|\bmacchiat', '☕'),
    (r'\bt[eè](\s|$)|\btisana|\binfuso', '🍵'),
    (r'\bcola\b|\bbibita|\baranciata|\bgassosa|\bisotonic|\benergy|\bsoda\b', '🥤'),
    (r'\bacqua\b', '💧'),
    (r'\blatte\b|\bbevanda di (soia|avena|mandorl|riso)', '🥛'),
    // integratori
    (r'\bcreatin|\bvitamin|\bomega|\bmagnesio|\bmultivitamin|\bintegratore', '💊'),
    (r'\bprotein|\bwhey\b|\bcaseina|\bgainer|\bmaltodestrin', '💪'),
    // frutta
    (r'\bbanan', '🍌'),
    (r'\barance?\b|\barancia\b|\bmandarin|\bclementin|\bpompelm', '🍊'),
    (r'\bmel[ae]\b|\bmele\b', '🍏'),
    (r'\bper[ae]\b', '🍐'),
    (r'\bpesc[ah]e?\b|\bpesche\b|\balbicocc|\bnettarin', '🍑'),
    (r'\bfragol', '🍓'),
    (r'\bciliegi', '🍒'),
    (r'\buv[ae]\b|\buvetta', '🍇'),
    (r'\bmirtill|\blampon|\bmore\b|\bfrutti di bosco|\bprugn|\bsusin', '🫐'),
    (r'\bdatter', '🌴'),
    (r'\banguri|\bcocomer', '🍉'),
    (r'\bmelon', '🍈'),
    (r'\bananas', '🍍'),
    (r'\bkiwi', '🥝'),
    (r'\bmango', '🥭'),
    (r'\bcocco\b', '🥥'),
    // verdure
    (r'\bpomodor|\bpassata|\bpelati\b|\bconcentrato di pomodoro', '🍅'),
    (r'\bcarot', '🥕'),
    (r'\bbroccol|\bcavolfior|\bcavolini', '🥦'),
    (r'\blattuga|\binsalata\b|\brucola|\bspinaci|\bradicchio|\bcavolo\b|\bverza|\bbietol', '🥬'),
    (r'\bpeperon', '🫑'),
    (r'\bmelanzan', '🍆'),
    (r'\bcetriol|\bzucchin', '🥒'),
    (r'\bcipoll', '🧅'),
    (r'\baglio\b', '🧄'),
    (r'\bpatate dolci|\bpatata dolce', '🍠'),
    (r'\bpatat', '🥔'),
    (r'\bfungh|\bchampignon|\bporcin', '🍄'),
    (r'\bmais\b|\bpolenta|\bpop corn', '🌽'),
    (r'\bavocado', '🥑'),
    (r'\bolive\b|\boliva\b', '🫒'),
    (r'\bsemi\b', '🌻'),
    (r'\bzucca\b', '🎃'),
    // cereali e pane
    (r'\bavena|\bmuesli|\bgranola|\bcorn ?flakes|\bcereali', '🥣'),
    (r'\bcracker|\bgrissin|\btaralli|\bbrezel|\bsalatin', '🥨'),
    (r'\bbaguette', '🥖'),
    (r'\bbagel', '🥯'),
    (r'\bpane\b|\bfocacci|\bpan ?carr', '🍞'),
    // proteine
    (r'\bgamber|\bmazzancoll|\bscamp', '🦐'),
    (r'\bpolpo', '🐙'),
    (r'\bcalamar|\bseppi', '🦑'),
    (r'\bcozze|\bvongole|\bostriche', '🦪'),
    (r'\btonno|\bsalmone|\bmerluzz|\borata|\bbranzin|\bsgombr|\bsardin|\balici|\bacciugh|\bpesce|\btrota|\bbaccal|\bsurimi|\bbastoncini', '🐟'),
    (r'\buov[ao]\b|\buova\b|\balbume|\btuorl', '🥚'),
    (r'\bsalsicc|\bwurstel|\bhot ?dog', '🌭'),
    (r'\bbistecc|\bmanzo|\bvitell|\bfilett|\bmacinat|\bmaiale|\blonza|\bcostin|\bfegato|\bcarne', '🥩'),
    (r'\bagnell|\bconigli', '🍖'),
    (r'\bpancett|\bguancial|\bbacon|\bspeck', '🥓'),
    (r'\bformagg|\bmozzarell|\bparmigian|\bgrana\b|\bricotta|\bpecorin|\bstracchin|\bgorgonzola|\bfeta\b|\bmascarpone|\bscamorz|\bprovol|\bemmental|\bfontina|\btaleggio', '🧀'),
    (r'\bburro di (arachid|mandorl)|\barachid|\bmandorl|\bpistacch|\banacard', '🥜'),
    (r'\bnoci\b|\bnocciol|\bcastagn', '🌰'),
    (r'\bburro\b|\bmargarina', '🧈'),
    (r'\bmiele|\bsciroppo', '🍯'),
    (r'\bolio\b', '🫒'),
    (r'\bketchup|\bmaionese|\bsenape|\bsalsa|\bsugo|\bragù|\bragu\b|\bpesto|\baceto', '🥫'),
    (r'\bceci\b|\bfagiol(?!ini)|\blenticch|\bpisell|\bedamame|\bhummus|\bsoia\b|\btofu|\btempeh|\bseitan', '🫘'),
    (r'\briso\b', '🍚'),
    (r'\bfarin|\bfarro|\borzo\b|\bquinoa|\bcouscous', '🌾'),
  ])
    (RegExp(p, caseSensitive: false), e),
];

/// Emoji dell'alimento: cerca parole note nel nome, altrimenti usa la categoria.
String foodEmoji(String name, String cat) {
  if (cat == 'Ricette') return catEmoji(cat);
  final n = name.toLowerCase();
  for (final (re, e) in _rules) {
    if (re.hasMatch(n)) return e;
  }
  return catEmoji(cat);
}
